model:
    device: "cuda:0"
    encoder: "tansformer"
    num_layer: 4
    vocab_size: 50
    d_model: 128
    hidden_size: 128
    drop_rate": 0.1
    num_class: 2

attention:
    type: "ScaledDotProductAttention"
    head_dim: 32
    n_heads: 2
    dropout: 0.1
    dct : 
        dct_x: true
        maxM: 32

dataset_conf:
    filter_conf:
        max_length: 2048
        min_length: 0
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    feature_extraction_conf:
        feature_type: 'fbank'
        num_mel_bins: 40
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 1
        num_f_mask: 1
        max_t: 50
        max_f: 30
    shuffle: true
    shuffle_conf:
        shuffle_size: 500
    batch_conf:
        batch_size: 16

dataset:
    train: "/home/junlin/myproject/MyMOdel/data/data.json"
    valid: ""

training_config:
    grad_clip: 5
    max_epoch: 40
    log_interval: 10
    accum_grad: 4

scheduler: warmuplr    
scheduler_conf:
    warmup_steps: 25000

optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 0.0001

